version: '3.1'

services:

  mongo:
    image: bitnami/mongodb:5.0
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_EXTRA_FLAGS: --wiredTigerCacheSizeGB=2
      MONGODB_ROOT_USER: root
      MONGODB_ROOT_PASSWORD: example
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: example
      MONGODB_DATABASE: examplejs

  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    ports:
      - 27080:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/