name: "Unit Test"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  live-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - name: Build the stack
        run: docker-compose up -d
      - name: Test
        run: npm run test
      - name: Destroy the stack
        run: docker-compose down